// Wire-protocol contract test.
//
// The strings below are the channel protocol shared by three codebases
// (Dart, Kotlin, Swift). If any assertion here fails, a refactor changed the
// wire protocol — either revert the Dart change or update Kotlin AND Swift
// (and this file) together in one commit.

import 'package:flutter_test/flutter_test.dart';
import 'package:sip_connect_flutter/src/sip_connect_platform.dart';

void main() {
  test('channel name is stable', () {
    expect(SipConnectPlatform.kChannelName, 'sip_connect_flutter');
  });

  test('Dart->native method names are stable', () {
    const expected = <String, String>{
      'kMethodModuleInitialize': 'Module_Initialize',
      'kMethodModuleUnInitialize': 'Module_UnInitialize',
      'kMethodModuleHomeFolder': 'Module_HomeFolder',
      'kMethodModuleVersionCode': 'Module_VersionCode',
      'kMethodModuleVersion': 'Module_Version',
      'kMethodAccountAdd': 'Account_Add',
      'kMethodAccountUpdate': 'Account_Update',
      'kMethodAccountRegister': 'Account_Register',
      'kMethodAccountUnregister': 'Account_Unregister',
      'kMethodAccountDelete': 'Account_Delete',
      'kMethodAccountGenInstId': 'Account_GenInstId',
      'kMethodCallInvite': 'Call_Invite',
      'kMethodCallReject': 'Call_Reject',
      'kMethodCallAccept': 'Call_Accept',
      'kMethodCallHold': 'Call_Hold',
      'kMethodCallGetHoldState': 'Call_GetHoldState',
      'kMethodCallGetSipHeader': 'Call_GetSipHeader',
      'kMethodCallGetStats': 'Call_GetStats',
      'kMethodCallMuteMic': 'Call_MuteMic',
      'kMethodCallMuteCam': 'Call_MuteCam',
      'kMethodCallSendDtmf': 'Call_SendDtmf',
      'kMethodCallPlayFile': 'Call_PlayFile',
      'kMethodCallPlayTone': 'Call_PlayTone',
      'kMethodCallStopPlayFile': 'Call_StopPlayFile',
      'kMethodCallRecordFile': 'Call_RecordFile',
      'kMethodCallStopRecordFile': 'Call_StopRecordFile',
      'kMethodCallTransferBlind': 'Call_TransferBlind',
      'kMethodCallTransferAttended': 'Call_TransferAttended',
      'kMethodCallStopRingtone': 'Call_StopRingtone',
      'kMethodCallUpgradeToVideo': 'Call_UpgradeToVideo',
      'kMethodCallAcceptVideoUpgrade': 'Call_AcceptVideoUpgrade',
      'kMethodCallBye': 'Call_Bye',
      'kMethodMixerSwitchToCall': 'Mixer_SwitchToCall',
      'kMethodMixerMakeConference': 'Mixer_MakeConference',
      'kMethodMessageSend': 'Message_Send',
      'kMethodSubscriptionAdd': 'Subscription_Add',
      'kMethodSubscriptionDelete': 'Subscription_Delete',
      'kMethodDvcGetPushKitToken': 'Dvc_GetPushKitToken',
      'kMethodDvcUpdCallKitDetails': 'Dvc_UpdCallKitDetails',
      'kMethodDvcGetCallKitUUID': 'Dvc_GetCallKitUUID',
      'kMethodDvcEndCallKitCall': 'Dvc_EndCallKitCall',
      'kMethodDvcSetForegroundMode': 'Dvc_SetForegroundMode',
      'kMethodDvcIsForegroundMode': 'Dvc_IsForegroundMode',
      'kMethodDvcSyncCallsState': 'Dvc_SyncCallsState',
      'kMethodDvcGetPlayoutNumber': 'Dvc_GetPlayoutDevices',
      'kMethodDvcGetRecordNumber': 'Dvc_GetRecordingDevices',
      'kMethodDvcGetVideoNumber': 'Dvc_GetVideoDevices',
      'kMethodDvcGetPlayout': 'Dvc_GetPlayoutDevice',
      'kMethodDvcGetRecording': 'Dvc_GetRecordingDevice',
      'kMethodDvcGetVideo': 'Dvc_GetVideoDevice',
      'kMethodDvcSetPlayout': 'Dvc_SetPlayoutDevice',
      'kMethodDvcSetRecording': 'Dvc_SetRecordingDevice',
      'kMethodDvcSetVideo': 'Dvc_SetVideoDevice',
      'kMethodDvcSetVideoParams': 'Dvc_SetVideoParams',
      'kMethodDvcSwitchCamera': 'Dvc_SwitchCamera',
      'kMethodVideoRendererCreate': 'Video_RendererCreate',
      'kMethodVideoRendererSetSrc': 'Video_RendererSetSrc',
      'kMethodVideoRendererDispose': 'Video_RendererDispose',
    };

    final actual = <String, String>{
      'kMethodModuleInitialize': SipConnectPlatform.kMethodModuleInitialize,
      'kMethodModuleUnInitialize': SipConnectPlatform.kMethodModuleUnInitialize,
      'kMethodModuleHomeFolder': SipConnectPlatform.kMethodModuleHomeFolder,
      'kMethodModuleVersionCode': SipConnectPlatform.kMethodModuleVersionCode,
      'kMethodModuleVersion': SipConnectPlatform.kMethodModuleVersion,
      'kMethodAccountAdd': SipConnectPlatform.kMethodAccountAdd,
      'kMethodAccountUpdate': SipConnectPlatform.kMethodAccountUpdate,
      'kMethodAccountRegister': SipConnectPlatform.kMethodAccountRegister,
      'kMethodAccountUnregister': SipConnectPlatform.kMethodAccountUnregister,
      'kMethodAccountDelete': SipConnectPlatform.kMethodAccountDelete,
      'kMethodAccountGenInstId': SipConnectPlatform.kMethodAccountGenInstId,
      'kMethodCallInvite': SipConnectPlatform.kMethodCallInvite,
      'kMethodCallReject': SipConnectPlatform.kMethodCallReject,
      'kMethodCallAccept': SipConnectPlatform.kMethodCallAccept,
      'kMethodCallHold': SipConnectPlatform.kMethodCallHold,
      'kMethodCallGetHoldState': SipConnectPlatform.kMethodCallGetHoldState,
      'kMethodCallGetSipHeader': SipConnectPlatform.kMethodCallGetSipHeader,
      'kMethodCallGetStats': SipConnectPlatform.kMethodCallGetStats,
      'kMethodCallMuteMic': SipConnectPlatform.kMethodCallMuteMic,
      'kMethodCallMuteCam': SipConnectPlatform.kMethodCallMuteCam,
      'kMethodCallSendDtmf': SipConnectPlatform.kMethodCallSendDtmf,
      'kMethodCallPlayFile': SipConnectPlatform.kMethodCallPlayFile,
      'kMethodCallPlayTone': SipConnectPlatform.kMethodCallPlayTone,
      'kMethodCallStopPlayFile': SipConnectPlatform.kMethodCallStopPlayFile,
      'kMethodCallRecordFile': SipConnectPlatform.kMethodCallRecordFile,
      'kMethodCallStopRecordFile': SipConnectPlatform.kMethodCallStopRecordFile,
      'kMethodCallTransferBlind': SipConnectPlatform.kMethodCallTransferBlind,
      'kMethodCallTransferAttended': SipConnectPlatform.kMethodCallTransferAttended,
      'kMethodCallStopRingtone': SipConnectPlatform.kMethodCallStopRingtone,
      'kMethodCallUpgradeToVideo': SipConnectPlatform.kMethodCallUpgradeToVideo,
      'kMethodCallAcceptVideoUpgrade': SipConnectPlatform.kMethodCallAcceptVideoUpgrade,
      'kMethodCallBye': SipConnectPlatform.kMethodCallBye,
      'kMethodMixerSwitchToCall': SipConnectPlatform.kMethodMixerSwitchToCall,
      'kMethodMixerMakeConference': SipConnectPlatform.kMethodMixerMakeConference,
      'kMethodMessageSend': SipConnectPlatform.kMethodMessageSend,
      'kMethodSubscriptionAdd': SipConnectPlatform.kMethodSubscriptionAdd,
      'kMethodSubscriptionDelete': SipConnectPlatform.kMethodSubscriptionDelete,
      'kMethodDvcGetPushKitToken': SipConnectPlatform.kMethodDvcGetPushKitToken,
      'kMethodDvcUpdCallKitDetails': SipConnectPlatform.kMethodDvcUpdCallKitDetails,
      'kMethodDvcGetCallKitUUID': SipConnectPlatform.kMethodDvcGetCallKitUUID,
      'kMethodDvcEndCallKitCall': SipConnectPlatform.kMethodDvcEndCallKitCall,
      'kMethodDvcSetForegroundMode': SipConnectPlatform.kMethodDvcSetForegroundMode,
      'kMethodDvcIsForegroundMode': SipConnectPlatform.kMethodDvcIsForegroundMode,
      'kMethodDvcSyncCallsState': SipConnectPlatform.kMethodDvcSyncCallsState,
      'kMethodDvcGetPlayoutNumber': SipConnectPlatform.kMethodDvcGetPlayoutNumber,
      'kMethodDvcGetRecordNumber': SipConnectPlatform.kMethodDvcGetRecordNumber,
      'kMethodDvcGetVideoNumber': SipConnectPlatform.kMethodDvcGetVideoNumber,
      'kMethodDvcGetPlayout': SipConnectPlatform.kMethodDvcGetPlayout,
      'kMethodDvcGetRecording': SipConnectPlatform.kMethodDvcGetRecording,
      'kMethodDvcGetVideo': SipConnectPlatform.kMethodDvcGetVideo,
      'kMethodDvcSetPlayout': SipConnectPlatform.kMethodDvcSetPlayout,
      'kMethodDvcSetRecording': SipConnectPlatform.kMethodDvcSetRecording,
      'kMethodDvcSetVideo': SipConnectPlatform.kMethodDvcSetVideo,
      'kMethodDvcSetVideoParams': SipConnectPlatform.kMethodDvcSetVideoParams,
      'kMethodDvcSwitchCamera': SipConnectPlatform.kMethodDvcSwitchCamera,
      'kMethodVideoRendererCreate': SipConnectPlatform.kMethodVideoRendererCreate,
      'kMethodVideoRendererSetSrc': SipConnectPlatform.kMethodVideoRendererSetSrc,
      'kMethodVideoRendererDispose': SipConnectPlatform.kMethodVideoRendererDispose,
    };
    expect(actual, expected);
  });

  test('native->Dart event names are stable', () {
    const expected = <String, String>{
      'kOnPushIncoming': 'OnPushIncoming',
      'kOnTrialModeNotif': 'OnTrialModeNotif',
      'kOnDevicesChanged': 'OnDevicesChanged',
      'kOnAccountRegState': 'OnAccountRegState',
      'kOnSubscriptionState': 'OnSubscriptionState',
      'kOnNetworkState': 'OnNetworkState',
      'kOnPlayerState': 'OnPlayerState',
      'kOnCallProceeding': 'OnCallProceeding',
      'kOnCallTerminated': 'OnCallTerminated',
      'kOnCallConnected': 'OnCallConnected',
      'kOnCallIncoming': 'OnCallIncoming',
      'kOnCallAcceptNotif': 'OnCallAcceptNotif',
      'kOnCallDtmfReceived': 'OnCallDtmfReceived',
      'kOnCallTransferred': 'OnCallTransferred',
      'kOnCallRedirected': 'OnCallRedirected',
      'kOnCallVideoUpgraded': 'OnCallVideoUpgraded',
      'kOnCallVideoUpgradeRequested': 'OnCallVideoUpgradeRequested',
      'kOnCallSwitched': 'OnCallSwitched',
      'kOnCallHeld': 'OnCallHeld',
      'kOnCallKitMuted': 'OnCallKitMuted',
      'kOnCallsSyncState': 'OnCallsSyncState',
      'kOnMessageSentState': 'OnMessageSentState',
      'kOnMessageIncoming': 'OnMessageIncoming',
      'kOnSipNotify': 'OnSipNotify',
      'kOnVuMeterLevel': 'OnVuMeterLevel',
    };
    final actual = <String, String>{
      'kOnPushIncoming': SipConnectPlatform.kOnPushIncoming,
      'kOnTrialModeNotif': SipConnectPlatform.kOnTrialModeNotif,
      'kOnDevicesChanged': SipConnectPlatform.kOnDevicesChanged,
      'kOnAccountRegState': SipConnectPlatform.kOnAccountRegState,
      'kOnSubscriptionState': SipConnectPlatform.kOnSubscriptionState,
      'kOnNetworkState': SipConnectPlatform.kOnNetworkState,
      'kOnPlayerState': SipConnectPlatform.kOnPlayerState,
      'kOnCallProceeding': SipConnectPlatform.kOnCallProceeding,
      'kOnCallTerminated': SipConnectPlatform.kOnCallTerminated,
      'kOnCallConnected': SipConnectPlatform.kOnCallConnected,
      'kOnCallIncoming': SipConnectPlatform.kOnCallIncoming,
      'kOnCallAcceptNotif': SipConnectPlatform.kOnCallAcceptNotif,
      'kOnCallDtmfReceived': SipConnectPlatform.kOnCallDtmfReceived,
      'kOnCallTransferred': SipConnectPlatform.kOnCallTransferred,
      'kOnCallRedirected': SipConnectPlatform.kOnCallRedirected,
      'kOnCallVideoUpgraded': SipConnectPlatform.kOnCallVideoUpgraded,
      'kOnCallVideoUpgradeRequested': SipConnectPlatform.kOnCallVideoUpgradeRequested,
      'kOnCallSwitched': SipConnectPlatform.kOnCallSwitched,
      'kOnCallHeld': SipConnectPlatform.kOnCallHeld,
      'kOnCallKitMuted': SipConnectPlatform.kOnCallKitMuted,
      'kOnCallsSyncState': SipConnectPlatform.kOnCallsSyncState,
      'kOnMessageSentState': SipConnectPlatform.kOnMessageSentState,
      'kOnMessageIncoming': SipConnectPlatform.kOnMessageIncoming,
      'kOnSipNotify': SipConnectPlatform.kOnSipNotify,
      'kOnVuMeterLevel': SipConnectPlatform.kOnVuMeterLevel,
    };
    expect(actual, expected);
  });
}
